export const flowcharts = [
  {
    id: "two-dismissal-rule",
    title: "Two Dismissal Rule on Voluntary Dismissals",
    subject: "Civil Procedure",
    width: 980,
    height: 640,
    nodes: [
      {
        id: "dismissal_notice",
        x: 340,
        y: 30,
        width: 300,
        height: 90,
        answer: "Plaintiff files a notice of voluntary dismissal",
        acceptedAnswers: [
          "plaintiff files notice of voluntary dismissal",
          "notice of voluntary dismissal by plaintiff",
          "voluntary dismissal notice",
        ],
      },
      {
        id: "same_claim_before",
        x: 340,
        y: 170,
        width: 300,
        height: 90,
        answer: "Was the same claim previously dismissed by plaintiff?",
        acceptedAnswers: [
          "same claim previously dismissed by plaintiff",
          "has plaintiff dismissed same claim before",
          "same claim dismissed before",
        ],
      },
      {
        id: "first_dismissal_effect",
        x: 80,
        y: 330,
        width: 320,
        height: 90,
        answer: "No. First notice dismissal is without prejudice",
        acceptedAnswers: [
          "first notice dismissal is without prejudice",
          "first dismissal without prejudice",
          "without prejudice",
        ],
      },
      {
        id: "second_dismissal_effect",
        x: 580,
        y: 330,
        width: 320,
        height: 90,
        answer: "Yes. Second notice operates as an adjudication on the merits",
        acceptedAnswers: [
          "second notice operates as adjudication on the merits",
          "second dismissal adjudication on the merits",
          "second dismissal with prejudice effect",
          "adjudication on the merits",
        ],
      },
      {
        id: "first_dismissal_refile",
        x: 80,
        y: 500,
        width: 320,
        height: 90,
        answer: "Plaintiff may refile (subject to limitations and claim rules)",
        acceptedAnswers: [
          "plaintiff may refile subject to limitations",
          "may refile",
          "refile allowed",
        ],
      },
      {
        id: "second_dismissal_preclusion",
        x: 580,
        y: 500,
        width: 320,
        height: 90,
        answer: "Refiling is barred by claim preclusion",
        acceptedAnswers: [
          "refiling barred by claim preclusion",
          "claim preclusion bars refiling",
          "res judicata bars refiling",
          "refiling barred",
        ],
      },
    ],
    arrows: [
      {
        from: "dismissal_notice",
        to: "same_claim_before",
        fromAnchor: "bottom",
        toAnchor: "top",
      },
      {
        from: "same_claim_before",
        to: "first_dismissal_effect",
        fromAnchor: "bottom-left",
        toAnchor: "top-right",
        label: "No",
      },
      {
        from: "same_claim_before",
        to: "second_dismissal_effect",
        fromAnchor: "bottom-right",
        toAnchor: "top-left",
        label: "Yes",
      },
      {
        from: "first_dismissal_effect",
        to: "first_dismissal_refile",
        fromAnchor: "bottom",
        toAnchor: "top",
      },
      {
        from: "second_dismissal_effect",
        to: "second_dismissal_preclusion",
        fromAnchor: "bottom",
        toAnchor: "top",
      },
    ],
  },
  {
    id: "negligence-core-elements",
    title: "Negligence Core Elements",
    subject: "Torts",
    width: 980,
    height: 760,
    nodes: [
      {
        id: "duty",
        x: 340,
        y: 20,
        width: 300,
        height: 80,
        answer: "Duty owed by defendant to plaintiff?",
        acceptedAnswers: [
          "duty owed by defendant to plaintiff",
          "duty",
          "duty owed",
        ],
      },
      {
        id: "breach",
        x: 340,
        y: 140,
        width: 300,
        height: 80,
        answer: "Breach of the duty (unreasonable conduct)?",
        acceptedAnswers: ["breach of duty", "breach", "unreasonable conduct"],
      },
      {
        id: "actual_cause",
        x: 340,
        y: 260,
        width: 300,
        height: 80,
        answer: "Actual cause (but-for causation)?",
        acceptedAnswers: [
          "actual cause",
          "but for causation",
          "cause in fact",
        ],
      },
      {
        id: "proximate_cause",
        x: 340,
        y: 380,
        width: 300,
        height: 80,
        answer: "Proximate cause (scope of foreseeable risk)?",
        acceptedAnswers: [
          "proximate cause",
          "foreseeable risk",
          "scope of liability",
        ],
      },
      {
        id: "damages",
        x: 340,
        y: 500,
        width: 300,
        height: 80,
        answer: "Legally cognizable damages?",
        acceptedAnswers: ["damages", "injury", "harm"],
      },
      {
        id: "liability_yes",
        x: 620,
        y: 620,
        width: 280,
        height: 90,
        answer: "Yes path: negligence liability",
        acceptedAnswers: [
          "negligence liability",
          "liable for negligence",
          "liability yes",
        ],
      },
      {
        id: "liability_no",
        x: 80,
        y: 620,
        width: 280,
        height: 90,
        answer: "No path at any element: no negligence liability",
        acceptedAnswers: [
          "no negligence liability",
          "not liable for negligence",
          "liability no",
        ],
      },
    ],
    arrows: [
      {
        from: "duty",
        to: "breach",
        fromAnchor: "bottom",
        toAnchor: "top",
        label: "Yes",
      },
      {
        from: "breach",
        to: "actual_cause",
        fromAnchor: "bottom",
        toAnchor: "top",
        label: "Yes",
      },
      {
        from: "actual_cause",
        to: "proximate_cause",
        fromAnchor: "bottom",
        toAnchor: "top",
        label: "Yes",
      },
      {
        from: "proximate_cause",
        to: "damages",
        fromAnchor: "bottom",
        toAnchor: "top",
        label: "Yes",
      },
      {
        from: "damages",
        to: "liability_yes",
        fromAnchor: "bottom-right",
        toAnchor: "top-left",
        label: "Yes",
      },
      {
        from: "duty",
        toPoint: { x: 220, y: 60 },
        fromAnchor: "left",
        label: "No",
        labelPosition: { x: 318, y: 54 },
        markerEnd: false,
      },
      {
        from: "breach",
        toPoint: { x: 220, y: 180 },
        fromAnchor: "left",
        label: "No",
        labelPosition: { x: 318, y: 174 },
        markerEnd: false,
      },
      {
        from: "actual_cause",
        toPoint: { x: 220, y: 300 },
        fromAnchor: "left",
        label: "No",
        labelPosition: { x: 318, y: 294 },
        markerEnd: false,
      },
      {
        from: "proximate_cause",
        toPoint: { x: 220, y: 420 },
        fromAnchor: "left",
        label: "No",
        labelPosition: { x: 318, y: 414 },
        markerEnd: false,
      },
      {
        from: "damages",
        toPoint: { x: 220, y: 540 },
        fromAnchor: "left",
        label: "No",
        labelPosition: { x: 318, y: 534 },
        markerEnd: false,
      },
      {
        id: "no-liability-trunk",
        fromPoint: { x: 220, y: 60 },
        fromSide: "bottom",
        to: "liability_no",
        toAnchor: "top",
      },
    ],
  },
  {
    id: "sales-predominant-purpose-test",
    title: "Predominant Purpose Test",
    subject: "Hybrid Transactions",
    prompt:
      "Rebuild the traditional all-or-nothing test for a transaction involving both goods and services.",
    width: 1100,
    height: 760,
    nodes: [
      {
        id: "ppt-hybrid-transaction",
        x: 360,
        y: 25,
        width: 380,
        height: 80,
        answer: "Hybrid transaction involving goods and services",
        acceptedAnswers: [
          "hybrid transaction",
          "mixed goods and services transaction",
          "goods and services",
        ],
      },
      {
        id: "ppt-core-question",
        x: 360,
        y: 145,
        width: 380,
        height: 95,
        answer: "What is the predominant factor, thrust, or purpose of the contract?",
        acceptedAnswers: [
          "predominant factor thrust or purpose",
          "predominant purpose of the contract",
          "what is the contract mainly about",
        ],
      },
      {
        id: "ppt-factors",
        x: 300,
        y: 285,
        width: 500,
        height: 115,
        answer: "Examine the agreement's language, price and payment structure, parties' businesses, and core deliverable",
        acceptedAnswers: [
          "language price businesses and core deliverable",
          "agreement language price allocation nature of businesses and core deliverable",
          "examine the transaction as a whole",
          "predominant purpose factors",
        ],
      },
      {
        id: "ppt-goods-question",
        x: 360,
        y: 445,
        width: 380,
        height: 85,
        answer: "Do the goods predominate?",
        acceptedAnswers: [
          "goods predominate",
          "do goods predominate",
          "are services merely incidental",
        ],
      },
      {
        id: "ppt-services-result",
        x: 55,
        y: 610,
        width: 430,
        height: 105,
        answer: "No. Services predominate, so Article 2 does not apply and common law governs",
        acceptedAnswers: [
          "services predominate so article 2 does not apply",
          "no article 2 common law governs",
          "services predominate",
          "common law governs",
        ],
      },
      {
        id: "ppt-goods-result",
        x: 615,
        y: 610,
        width: 430,
        height: 105,
        answer: "Yes. Goods predominate, so Article 2 applies to the entire transaction",
        acceptedAnswers: [
          "goods predominate so article 2 applies to the entire transaction",
          "article 2 applies to entire transaction",
          "goods predominate",
          "article 2 applies",
        ],
      },
    ],
    arrows: [
      {
        from: "ppt-hybrid-transaction",
        to: "ppt-core-question",
        fromAnchor: "bottom",
        toAnchor: "top",
      },
      {
        from: "ppt-core-question",
        to: "ppt-factors",
        fromAnchor: "bottom",
        toAnchor: "top",
      },
      {
        from: "ppt-factors",
        to: "ppt-goods-question",
        fromAnchor: "bottom",
        toAnchor: "top",
      },
      {
        from: "ppt-goods-question",
        to: "ppt-services-result",
        fromAnchor: "bottom-left",
        toAnchor: "top-right",
        label: "No",
      },
      {
        from: "ppt-goods-question",
        to: "ppt-goods-result",
        fromAnchor: "bottom-right",
        toAnchor: "top-left",
        label: "Yes",
      },
    ],
  },
  {
    id: "sales-gravamen-of-the-action",
    title: "Gravamen of the Action",
    subject: "Hybrid Transactions",
    prompt:
      "Trace the claim-centered test by identifying the particular source of the complaint or injury.",
    width: 1000,
    height: 690,
    nodes: [
      {
        id: "gravamen-hybrid-claim",
        x: 330,
        y: 25,
        width: 340,
        height: 80,
        answer: "Claim arising from a hybrid transaction",
        acceptedAnswers: [
          "claim from a hybrid transaction",
          "hybrid transaction claim",
          "hybrid transaction",
        ],
      },
      {
        id: "gravamen-source-question",
        x: 315,
        y: 160,
        width: 370,
        height: 90,
        answer: "What is the source of the complaint or injury?",
        acceptedAnswers: [
          "source of the complaint",
          "source of the injury",
          "what caused the lawsuit",
          "gravamen of the claim",
        ],
      },
      {
        id: "gravamen-isolate-issue",
        x: 300,
        y: 310,
        width: 400,
        height: 95,
        answer: "Isolate whether the failure occurred in the goods or services component",
        acceptedAnswers: [
          "isolate goods or services component",
          "goods or services component",
          "identify whether goods or services caused the harm",
        ],
      },
      {
        id: "gravamen-goods-result",
        x: 45,
        y: 510,
        width: 410,
        height: 120,
        answer: "Goods caused the complaint: Article 2 applies to the goods-based claim",
        acceptedAnswers: [
          "goods caused complaint article 2 applies",
          "article 2 applies to goods claim",
          "defective goods article 2 applies",
          "goods based claim",
        ],
      },
      {
        id: "gravamen-services-result",
        x: 545,
        y: 510,
        width: 410,
        height: 120,
        answer: "Services caused the complaint: other law applies to the services-based claim",
        acceptedAnswers: [
          "services caused complaint other law applies",
          "other law applies to services claim",
          "faulty services common law applies",
          "services based claim",
        ],
      },
    ],
    arrows: [
      {
        from: "gravamen-hybrid-claim",
        to: "gravamen-source-question",
        fromAnchor: "bottom",
        toAnchor: "top",
      },
      {
        from: "gravamen-source-question",
        to: "gravamen-isolate-issue",
        fromAnchor: "bottom",
        toAnchor: "top",
      },
      {
        from: "gravamen-isolate-issue",
        to: "gravamen-goods-result",
        fromAnchor: "bottom-left",
        toAnchor: "top-right",
        label: "Goods",
      },
      {
        from: "gravamen-isolate-issue",
        to: "gravamen-services-result",
        fromAnchor: "bottom-right",
        toAnchor: "top-left",
        label: "Services",
      },
    ],
  },
  {
    id: "sales-2022-ucc-amendments",
    title: "2022 Amendments to UCC Section 2-102",
    subject: "Hybrid Transactions",
    prompt:
      "Apply the enacted-amendment gate and the new two-tier rule for the sale-of-goods aspects of a hybrid transaction.",
    width: 1100,
    height: 980,
    nodes: [
      {
        id: "amendments-enacted-question",
        x: 365,
        y: 25,
        width: 370,
        height: 85,
        answer: "Has the governing jurisdiction enacted the 2022 amendments?",
        acceptedAnswers: [
          "has jurisdiction enacted 2022 amendments",
          "jurisdiction enacted the amendments",
          "check enactment",
        ],
      },
      {
        id: "amendments-not-enacted",
        x: 40,
        y: 170,
        width: 400,
        height: 105,
        answer: "No. Use the jurisdiction's pre-amendment hybrid-transaction test",
        acceptedAnswers: [
          "use pre amendment test",
          "use predominant purpose or gravamen",
          "pre amendment hybrid transaction test",
        ],
      },
      {
        id: "amendments-hybrid-question",
        x: 655,
        y: 170,
        width: 405,
        height: 105,
        answer: "Yes. Is this a hybrid transaction involving a sale of goods and a non-goods aspect?",
        acceptedAnswers: [
          "is this a hybrid transaction",
          "sale of goods and non goods aspect",
          "hybrid transaction involving goods and services",
        ],
      },
      {
        id: "amendments-ordinary-scope",
        x: 845,
        y: 335,
        width: 215,
        height: 105,
        answer: "No. Apply ordinary Article 2 scope analysis",
        acceptedAnswers: [
          "ordinary article 2 scope analysis",
          "apply ordinary scope analysis",
          "not a hybrid transaction",
        ],
      },
      {
        id: "amendments-predominance-analysis",
        x: 405,
        y: 335,
        width: 400,
        height: 105,
        answer: "Yes. Determine which aspects of the transaction predominate",
        acceptedAnswers: [
          "determine which aspects predominate",
          "which aspects of the transaction predominate",
          "sale of goods aspects predominate",
        ],
      },
      {
        id: "amendments-factors",
        x: 475,
        y: 500,
        width: 405,
        height: 120,
        answer: "Consider agreement language, price allocation, parties' purposes, and the nature of their businesses",
        acceptedAnswers: [
          "language price purpose and nature of businesses",
          "agreement language price allocation parties purposes and businesses",
          "predominance factors",
        ],
      },
      {
        id: "amendments-goods-question",
        x: 485,
        y: 680,
        width: 385,
        height: 90,
        answer: "Do the sale-of-goods aspects predominate?",
        acceptedAnswers: [
          "do sale of goods aspects predominate",
          "sale of goods aspects predominate",
          "goods aspects predominate",
        ],
      },
      {
        id: "amendments-goods-predominate-result",
        x: 55,
        y: 830,
        width: 455,
        height: 115,
        answer: "Yes. Article 2 applies to the transaction; other law may still apply to non-goods aspects",
        acceptedAnswers: [
          "article 2 applies to transaction other law may apply to non goods aspects",
          "article 2 applies to the transaction",
          "goods predominate article 2 applies",
        ],
      },
      {
        id: "amendments-goods-do-not-predominate-result",
        x: 590,
        y: 830,
        width: 455,
        height: 115,
        answer: "No. Only Article 2 provisions relating primarily to the goods aspects apply; transaction-wide provisions do not",
        acceptedAnswers: [
          "only article 2 provisions relating to goods aspects apply",
          "goods provisions apply transaction wide provisions do not",
          "article 2 applies only to goods aspects",
          "goods do not predominate",
        ],
      },
    ],
    arrows: [
      {
        from: "amendments-enacted-question",
        to: "amendments-not-enacted",
        fromAnchor: "bottom-left",
        toAnchor: "top-right",
        label: "No",
      },
      {
        from: "amendments-enacted-question",
        to: "amendments-hybrid-question",
        fromAnchor: "bottom-right",
        toAnchor: "top-left",
        label: "Yes",
      },
      {
        from: "amendments-hybrid-question",
        to: "amendments-predominance-analysis",
        fromAnchor: "bottom-left",
        toAnchor: "top-right",
        label: "Yes",
      },
      {
        from: "amendments-hybrid-question",
        to: "amendments-ordinary-scope",
        fromAnchor: "bottom-right",
        toAnchor: "top",
        label: "No",
      },
      {
        from: "amendments-predominance-analysis",
        to: "amendments-factors",
        fromAnchor: "bottom",
        toAnchor: "top",
      },
      {
        from: "amendments-factors",
        to: "amendments-goods-question",
        fromAnchor: "bottom",
        toAnchor: "top",
      },
      {
        from: "amendments-goods-question",
        to: "amendments-goods-predominate-result",
        fromAnchor: "bottom-left",
        toAnchor: "top-right",
        label: "Yes",
      },
      {
        from: "amendments-goods-question",
        to: "amendments-goods-do-not-predominate-result",
        fromAnchor: "bottom-right",
        toAnchor: "top-left",
        label: "No",
      },
    ],
  },
];
