import { readableFlowchartLayout } from "./flowchartLayout.js";

// Course scope comes from the finished outline; context records point to the
// local class materials. Public links identify the controlling rule text.
const UCC = "https://www.law.cornell.edu/ucc/";
const USC = "https://www.law.cornell.edu/uscode/text/15/";
const CISG = "https://uncitral.un.org/en/texts/salegoods/conventions/sale_of_goods/cisg";
const FL_SCOPE = "https://www.flsenate.gov/Laws/Statutes/2025/672.102";

function source(rule) {
  if (rule === "CISG") return { sourceUrl: CISG, sourceLabel: "CISG · Articles 1–3, 6 and 10" };
  if (rule === "FL-672.102") return { sourceUrl: FL_SCOPE, sourceLabel: "Florida Statutes § 672.102" };
  if (rule.startsWith("15-")) return { sourceUrl: USC + rule.slice(3), sourceLabel: `15 U.S.C. § ${rule.slice(3)}` };
  return { sourceUrl: UCC + rule.split("-")[0] + "/" + rule, sourceLabel: `UCC § ${rule}` };
}

// Row keys stay stable when wording or ordering changes. Short aliases preserve
// the tested distinction; the indicator supplies the rest of the question.
const a = (key, indicator, answer, ...acceptedAnswers) => ({ key, indicator, answer, acceptedAnswers });
const c = (key, title, ...answers) => ({ key, title, answers });

function grid(id, title, section, rule, columns, context = "", prompt = "Use each clue to recall the rule, requirement, or legal consequence.") {
  const prefix = `sales-${id}`;
  return {
    id: prefix, type: "sporcle-grid", clueLayout: "above", title, prompt, ...source(rule),
    courseSources: [`Finished Sales and Leases Outline · ${section}`, ...(context ? [context] : [])],
    columns: columns.map(({ key, title: columnTitle, answers }) => ({
      id: `${prefix}-${key}`, title: columnTitle,
      answers: answers.map(({ key: rowKey, ...row }) => ({ id: `${prefix}-${rowKey}`, ...row })),
    })),
  };
}

const scopeQuestions = [
  grid("good-faith", "Good Faith and the Role of the Code", "I and III", "1-304", [
    c("faith", "Revised Article 1 · § 1-201(b)(20)",
      a("honesty", "Subjective component of good faith", "honesty in fact", "honesty"),
      a("fair", "Objective component", "observance of reasonable commercial standards of fair dealing", "reasonable commercial standards of fair dealing"),
      a("stage", "§ 1-304 applies to performance and…", "enforcement", "contract enforcement")),
    c("code", "Agreement and Supplementary Law",
      a("default", "UCC gap fillers supply missing…", "contract terms", "terms"),
      a("common", "Undisplaced common-law principles may…", "supplement the UCC", "supplement")),
  ], "Original outline · Sales Systems; Finished outline · §§ 1-103, 1-304", "Use the revised Article 1 definition of good faith. A trade's reliance on private practices is not itself a categorical exemption from Article 2."),
  grid("goods", "Goods and the Scope of Article 2", "I", "2-105", [
    c("definition", "The Goods Requirement",
      a("movable", "Physical characteristic", "movable", "moveable"),
      a("identification", "Time when that characteristic matters", "identification to the contract", "when identified to the contract"),
      a("custom", "Custom-built goods: included or excluded?", "included", "included as goods")),
    c("exclusions", "Excluded from the Definition",
      a("money", "Money excluded by § 2-105(1)", "money in which the price is to be paid", "money used to pay the price"),
      a("securities", "Investment assets expressly excluded", "investment securities", "securities"),
      a("claims", "Intangible claims, such as royalty rights", "things in action", "choses in action")),
  ], "Class 4 · slides 48–50; Problem Set 1 · Problem 1.5"),
  grid("realty", "Goods Severed from Real Estate", "I", "2-107", [
    c("severance", "Who Must Sever?",
      a("structure", "Structure or minerals: required severing party", "seller", "the seller"),
      a("crops", "Growing crops: permitted severing party", "buyer or seller", "either party"),
      a("timber", "Timber to be cut: permitted severing party", "buyer or seller", "either party"),
      a("other", "Other attached things: required effect of severance", "no material harm to the realty", "without material harm to the land")),
    c("application", "Apply the Distinction",
      a("house", "House sold with land, to remain attached: governing category", "real property", "real estate", "realty"),
      a("apples", "Apples sold to be picked: governing UCC article", "Article 2", "UCC 2", "2")),
  ], "Class 7 · slides 4–12; Problem Set 2 · Problem 2.6"),
  grid("agreement-hierarchy", "Agreement Before Gap Fillers", "I", "1-303", [
    c("hierarchy", "Priority When Consistent Construction Fails",
      a("express", "1 · Highest priority", "express terms", "express contract terms"),
      a("performance", "2 · Current contract", "course of performance", "COP"),
      a("dealing", "3 · Earlier transactions", "course of dealing", "COD"),
      a("usage", "4 · Industry practice", "usage of trade", "trade usage", "TU")),
    c("method", "Interpretation Method",
      a("consistent", "Try this before applying the hierarchy", "construe the terms consistently", "consistent construction", "read consistently"),
      a("gap", "Use a UCC default only if this remains", "a gap in the agreement", "gap", "missing term"),
      a("common", "Common law supplements the UCC unless it is…", "displaced by the UCC", "displaced", "displaced by a particular UCC provision")),
  ], "Class 3 · slide 17; Class 4 · slides 5, 11–14; Ragus v. Chicago", "Reconstruct the priority order, then recall when default rules are needed. See also UCC § 1-103."),
  grid("delivery-context", "Application: A Repeated Delivery Practice", "I", "1-303", [
    c("identify", "Which Source Supplies the Delivery Term?",
      a("same", "Three deliveries accepted without objection under this contract", "course of performance", "COP"),
      a("prior", "Delivery practice from earlier contracts between these parties", "course of dealing", "COD"),
      a("industry", "Regular industry practice, with no earlier dealings", "usage of trade", "trade usage", "TU")),
    c("default", "Only If the Agreement Leaves a Gap",
      a("business", "Default delivery place if seller has a business", "seller's place of business", "seller business"),
      a("residence", "Default if seller has no business location", "seller's residence", "seller home"),
      a("identified", "Identified goods known by both parties to be elsewhere", "that other place", "location of the identified goods")),
  ], "Class 3 · slides 13–17; Class 4 · slides 2–14; Problem Set 1 · Problem 1.2", "A supply contract omits the delivery location. Identify the relevant practice in each variation, then apply § 2-308 only if a gap remains."),
  grid("merchant", "Merchant Status Depends on the Rule", "I", "2-104", [
    c("definition", "Ways to Qualify",
      a("dealer", "Regular commercial activity", "deals in goods of the kind", "dealer in goods of the kind"),
      a("expertise", "Occupational expertise concerning the transaction", "knowledge or skill about the practices or goods involved", "special knowledge of practices or goods"),
      a("agent", "Expertise may be attributed through an employed…", "agent or broker", "agent", "broker")),
    c("distinguish", "Choose the Relevant Category",
      a("business", "Firm offers and confirmations: relevant expertise", "general business practices", "business practices"),
      a("quality", "Merchantability: seller must be a merchant with respect to…", "goods of that kind", "the goods of that kind"),
      a("private", "Private reunion sale: capacity the merchant exception requires", "mercantile capacity", "commercial capacity")),
  ], "Class 4 · slides 51–55; Original outline · § 2-104 Comment 2", "Do not apply one universal merchant test to every provision. Use the rule's required type of expertise and the capacity in which the person acts."),
  grid("florida-hybrid", "Florida's Enacted Hybrid-Transaction Rule", "I", "FL-672.102", [
    c("branches", "Apply § 672.102 to a Covered Transaction",
      a("minor", "Goods do not predominate: provisions that apply relate primarily to…", "the sale-of-goods aspects", "goods aspects", "sale of goods aspects"),
      a("whole", "Goods do not predominate: provisions about the transaction as a whole…", "do not apply", "are inapplicable"),
      a("major", "Goods predominate: Article 2 applies to…", "the transaction", "the whole transaction"),
      a("other", "Goods predominate: other law may still govern…", "non-goods aspects", "aspects not related to the sale of goods")),
  ], "Class 6 · slides 4–9", "Florida enacted the hybrid rule in 2025. Assume the amended statute governs this transaction; do not substitute the older all-or-nothing test."),
  grid("cisg", "CISG Scope and the Microgem Lesson", "I · supplemental scope context", "CISG", [
    c("scope", "International Scope",
      a("places", "Article 1(1)(a): relevant location of the parties", "places of business in different contracting states", "businesses in different contracting states"),
      a("apparent", "International character must be apparent by…", "contract formation", "formation", "conclusion of the contract"),
      a("closest", "Several business locations: choose the one with…", "the closest relationship to the contract and its performance", "closest relationship to contract and performance"),
      a("consumer", "Known personal, family, or household purchases are generally…", "excluded", "not covered")),
    c("choice", "Choice of Law",
      a("exclude", "Article 6 permits parties to…", "exclude the CISG", "opt out of the CISG", "opt out"),
      a("microgem", "Microgem: a generic New York-law clause was…", "insufficient to exclude the CISG", "not an opt out", "insufficient")),
  ], "Class 6 · slides 49–55; Microgem v. Homecast; Problem Set 2 · Problem 2.5", "Recall the Article 1(1)(a) route and the course's choice-of-law example. The consumer exclusion has an exception when the seller neither knew nor ought to have known the personal use."),
];

const formationQuestions = [
  grid("hill-gateway", "Case Application: Hill v. Gateway", "II", "2-204", [
    c("case", "Seventh Circuit's Analysis in Hill",
      a("period", "Contractual return period in the case", "30 days", "thirty days"),
      a("act", "Conduct the court treated as acceptance", "keeping the computer beyond the return period", "keeping the computer beyond 30 days"),
      a("term", "Disputed term enforced by the court", "arbitration clause", "arbitration agreement", "arbitration")),
    c("reasoning", "Identify the Court's Reasoning",
      a("timing", "Issue was how and when the contract was…", "formed", "formed by acceptance"),
      a("read", "Did failure to read alone defeat the accepted terms?", "no", "not by itself")),
  ], "Hill v. Gateway 2000, 105 F.3d 1147 · supplied case PDF, pages 2–5", "Recall the holding on these facts and the court's accept-or-return analysis. Do not treat Hill as a universal rule that every term delivered after purchase binds the buyer."),
  grid("formation", "Flexible Formation and Offer Acceptance", "II", "2-204", [
    c("formation", "Formation Under § 2-204",
      a("conduct", "Agreement can be shown by words or…", "conduct", "conduct recognizing a contract"),
      a("intent", "Open terms do not defeat formation if parties intend…", "to make a contract", "to contract"),
      a("remedy", "Open terms still require a reasonably certain basis for…", "an appropriate remedy", "giving an appropriate remedy", "a remedy"),
      a("moment", "Must the exact moment of formation be known?", "no", "not necessary")),
    c("acceptance", "Acceptance Under § 2-206",
      a("medium", "Default manner and medium of acceptance", "reasonable under the circumstances", "any reasonable manner and medium"),
      a("shipment", "Order for prompt shipment: alternative to actually shipping", "a prompt promise to ship", "promise to ship promptly")),
  ], "Finished outline · §§ 2-204–2-206", "Recall the flexible formation rules. The acceptance column applies § 2-206."),
  grid("firm-offers", "Firm Offers Without Consideration", "II", "2-205", [
    c("requirements", "Required Assurances",
      a("merchant", "Offeror's status", "merchant", "a merchant"),
      a("writing", "Form of offer", "signed writing", "a signed writing"),
      a("assurance", "What the writing must assure", "the offer will be held open", "held open", "assurance of irrevocability"),
      a("separate", "Assurance on offeree's form must be…", "separately signed by the offeror", "separately signed")),
    c("time", "Period of Irrevocability",
      a("stated", "If the offer states a period", "the stated time", "time stated"),
      a("unstated", "If no period is stated", "a reasonable time", "reasonable time"),
      a("cap", "Statutory maximum without consideration", "three months", "3 months")),
  ]),
  grid("shipment-acceptance", "Application: Shipping Substitute Goods", "II", "2-206", [
    c("ordinary", "An Order Invites Prompt Shipment",
      a("conforming", "Seller promptly ships conforming goods", "acceptance", "accepts the offer"),
      a("wrong", "Seller ships nonconforming goods without accommodation notice", "acceptance and breach", "both acceptance and breach"),
      a("notice", "To make a nonconforming shipment merely an accommodation, notify…", "seasonably", "seasonably notify the buyer")),
    c("accommodation", "A Seasonably Identified Accommodation",
      a("counter", "Legal character of the substitute shipment", "counteroffer", "a counteroffer"),
      a("reject", "May the buyer decline the accommodation?", "yes", "yes without accepting"),
      a("begin", "Beginning performance as acceptance requires notice within…", "a reasonable time", "reasonable time")),
  ], "Finished outline · § 2-206", "A buyer orders a specified model for immediate shipment. The seller sends a different model. Distinguish an ordinary nonconforming acceptance from a seasonably identified accommodation."),
  grid("statute-frauds", "Statute of Frauds: Writing and Merchant Confirmation", "I–II", "2-201", [
    c("writing", "Basic Rule in the Course's UCC Text",
      a("price", "Price triggering § 2-201(1)", "$500 or more", "500 or more", "at least 500 dollars"),
      a("signature", "Required signer", "party against whom enforcement is sought", "party to be charged"),
      a("quantity", "Enforcement cannot exceed the stated…", "quantity", "quantity of goods")),
    c("confirmation", "Between Merchants",
      a("sender", "Confirmation must be sufficient against…", "the sender", "sender"),
      a("timely", "Confirmation must arrive within…", "a reasonable time", "reasonable time"),
      a("knowledge", "Recipient must have reason to know…", "its contents", "contents of the confirmation"),
      a("objection", "Recipient's objection must be in this form", "writing", "written notice"),
      a("deadline", "Objection deadline after receipt", "10 days", "ten days")),
  ], "Class 4 · slides 51–55; Problem Set 1 · Problem 1.6", "The merchant-confirmation rule removes a writing defense; silence alone does not prove that the alleged oral agreement existed."),
  grid("frauds-exceptions", "Statute of Frauds: Three Exceptions", "I–II", "2-201", [
    c("custom", "Specially Manufactured Goods",
      a("unsuitable", "Goods must be unsuitable for…", "sale to others in the ordinary course", "ordinary resale to others"),
      a("start", "Seller must have substantially begun manufacture or made…", "commitments for procurement", "procurement commitments"),
      a("before", "Required action must precede notice of…", "repudiation", "buyer repudiation")),
    c("others", "Admission and Performance",
      a("admission", "Where a qualifying admission is made", "in court", "pleading or testimony in court"),
      a("limit", "Judicial admission is enforceable only to the…", "quantity admitted", "admitted quantity"),
      a("payment", "Payment exception requires payment made and…", "accepted", "payment accepted"),
      a("receipt", "Goods exception requires goods received and…", "accepted", "goods accepted")),
  ]),
  grid("additional-terms", "Battle of the Forms: Additional Terms", "II", "2-207", [
    c("formation", "Section 2-207(1)",
      a("expression", "Required quality of an acceptance", "definite and seasonable", "definite and timely"),
      a("conditional", "Exception: acceptance expressly conditional on…", "assent to additional or different terms", "assent to the new terms"),
      a("confirmation", "Also addresses writings confirming…", "an existing agreement", "a prior agreement")),
    c("terms", "Additional Terms Under § 2-207(2)",
      a("nonmerchant", "Outside a transaction between merchants: new terms are…", "proposals", "proposals for addition"),
      a("limit", "Merchant exception 1: offer expressly…", "limits acceptance to its own terms", "limits acceptance to the terms of the offer"),
      a("material", "Merchant exception 2: new term causes a…", "material alteration", "material change"),
      a("object", "Merchant exception 3: prior or timely…", "objection", "notice of objection")),
  ], "Finished outline · § 2-207; Belden v. American Electronic Components", "Formation and inclusion of a proposed term are separate questions. The three merchant exceptions are alternatives: any one excludes the added term."),
  grid("conduct-forms", "Conflicting Forms and a Contract by Conduct", "II", "2-207", [
    c("conduct", "Writings Do Not Establish a Contract",
      a("both", "Whose conduct must recognize a contract under subsection (3)?", "both parties", "conduct by both parties"),
      a("agreed", "Written terms retained", "terms on which the writings agree", "agreed terms"),
      a("supplement", "Source of supplementary terms", "the UCC", "UCC supplementary provisions", "UCC gap fillers")),
    c("different", "Conflicting Terms",
      a("knockout", "Course's approach to mutually conflicting terms", "knockout rule", "knock out rule"),
      a("effect", "Under that approach, conflicting terms are…", "removed from both forms", "both knocked out", "knocked out"),
      a("variation", "Treatment of different terms under subsection (2) varies by…", "jurisdiction", "court", "governing jurisdiction")),
  ], "Belden v. American Electronic Components; Finished outline · § 2-207", "An expressly conditional reply gets no assent, but both parties perform. Apply subsection (3). Keep that statutory rule distinct from jurisdiction-dependent treatment of different terms under subsection (2)."),
  grid("parol-evidence", "Parol Evidence and Contract Modification", "II", "2-202", [
    c("writing", "A Final Written Expression",
      a("contradict", "Prior agreement or contemporaneous oral terms may not…", "contradict the final writing", "contradict it"),
      a("context", "COP, COD, and trade usage may explain or…", "supplement", "supplement the writing"),
      a("additional", "Additional terms must be…", "consistent", "consistent additional terms"),
      a("complete", "Additional terms barred if writing is complete and…", "exclusive", "exclusive statement of terms")),
    c("modification", "Later Modification · § 2-209",
      a("consideration", "New consideration required?", "no", "not required"),
      a("faith", "Modification must satisfy the obligation of…", "good faith", "good faith performance"),
      a("frauds", "If contract as modified is within § 2-201, satisfy…", "the statute of frauds", "statute of frauds", "writing requirements")),
  ]),
];

const warrantyQuestions = [
  grid("express-warranty", "Express Warranties: Creation and Limits", "III", "2-313", [
    c("create", "Ways to Create an Express Warranty",
      a("fact", "Specific factual representation", "affirmation of fact", "statement of fact"),
      a("promise", "Commitment concerning the goods", "promise", "a promise"),
      a("description", "Identification of the goods' characteristics", "description", "description of the goods"),
      a("sample", "Physical exemplar", "sample or model", "sample", "model")),
    c("limits", "Connection to the Agreement",
      a("basis", "Representation must become part of the…", "basis of the bargain", "bargain"),
      a("magic", "Are formal words such as guarantee required?", "no", "not required"),
      a("opinion", "Mere commendation or opinion is ordinarily…", "puffery", "not a warranty")),
  ], "Class 7 · slides 25–30"),
  grid("merchantability", "The Six Merchantability Standards", "III", "2-314", [
    c("standards", "Goods Must Meet These Minimums",
      a("trade", "Trade acceptance under the contract description", "pass without objection in the trade", "pass without trade objection"),
      a("fungible", "Fungible goods within the description", "fair average quality", "of fair average quality"),
      a("ordinary", "Suitability for use", "fit for ordinary purposes", "ordinary purpose fitness"),
      a("uniform", "Within permitted variations, units must be even in…", "kind quality and quantity", "kind quantity and quality"),
      a("packaging", "As the agreement requires, adequate…", "containment packaging and labeling", "contained packaged and labeled"),
      a("label", "Conformity to promises or facts on…", "the container or label", "container or label")),
  ], "Class 7 · slides 31–33"),
  grid("merchantability-claim", "Proving a Merchantability Claim", "III", "2-314", [
    c("claim", "Course's Claim Checklist",
      a("seller", "Required kind of seller", "merchant with respect to goods of that kind", "merchant of goods of that kind"),
      a("defect", "Goods' condition at sale", "not merchantable", "unmerchantable", "defective at sale"),
      a("harm", "Plaintiff must suffer…", "injury or damages", "injury", "damages"),
      a("cause", "Required link from defect to loss", "actual and proximate causation", "cause in fact and proximate cause"),
      a("notice", "Procedural requirement under § 2-607", "timely notice to the seller", "notice of breach to seller")),
    c("distinction", "Warranty and Negligence",
      a("care", "Does due care alone defeat an established warranty breach?", "no", "no negligence is not required")),
  ], "Class 7 · slide 33; Finished outline · § 2-314 Comment 13"),
  grid("fitness", "Fitness for a Particular Purpose", "III", "2-315", [
    c("requirements", "At the Time of Contracting",
      a("purpose", "Seller has reason to know the buyer's…", "particular purpose", "special purpose"),
      a("reliance", "Seller has reason to know buyer relies on seller's…", "skill or judgment", "skill and judgment"),
      a("actual", "Buyer must actually…", "rely on the seller's skill or judgment", "rely on seller", "actually rely")),
    c("compare", "Distinguish Merchantability",
      a("merchant", "Must this seller be a merchant?", "no", "not required"),
      a("ordinary", "Can goods be fit for ordinary use yet breach this warranty?", "yes", "yes if unfit for the particular purpose")),
  ], "Class 7 · slide 34; Finished outline · Leal v. Holtvogt"),
  grid("warranty-application", "Application: Match the Warranty to the Facts", "III", "2-313", [
    c("identify", "Which Quality Warranty Is Implicated?",
      a("promise", "Seller's factual horsepower promise is part of the bargain", "express warranty", "express"),
      a("ordinary", "Merchant sells a chair that collapses during ordinary sitting", "merchantability", "IWOM", "implied warranty of merchantability"),
      a("special", "Buyer relies on seller's advice for a disclosed unusual industrial use", "fitness for a particular purpose", "IWFPP", "implied warranty of fitness")),
    c("phillips", "Phillips v. Cricket Lighters · Pennsylvania",
      a("who", "§ 2-318 identifies who may recover; breach still requires…", "an unmerchantable product", "proof of unmerchantability", "a breach of warranty"),
      a("purpose", "Ordinary purpose the court used for the lighter", "producing a flame for adult use", "adult use to produce a flame"),
      a("holding", "Court's result on merchantability", "no breach of merchantability", "merchantable", "no merchantability breach")),
  ], "Class 7 · slides 35–39", "Identify the warranty suggested by each new fact pattern. Then recall the specific holding in Phillips, rather than treating household-beneficiary status as proof of a defect. See also §§ 2-314, 2-315 and 2-318."),
  grid("disclaimers", "Sales Warranty Disclaimers", "III", "2-316", [
    c("ordinary", "Section 2-316(2) Route",
      a("word", "Merchantability disclaimer must mention…", "merchantability", "the word merchantability"),
      a("oral", "Must every sales merchantability disclaimer be written?", "no", "may be oral"),
      a("written", "If written, it must be…", "conspicuous", "conspicuous writing"),
      a("fitness", "Fitness disclaimer requires…", "a conspicuous writing", "written and conspicuous")),
    c("express", "An Existing Express Warranty",
      a("consistent", "First try to construe warranty and disclaimer…", "consistently", "as consistent"),
      a("conflict", "If reasonable consistent construction is impossible, disclaimer is…", "inoperative to the extent of the conflict", "ineffective to the extent inconsistent")),
  ], "Finished outline · § 2-316", "Apply subsection (2), subject to the alternative routes in subsection (3), parol-evidence rules, and any applicable consumer-warranty law."),
  grid("disclaimer-exceptions", "As Is, Inspection, and Warranty Priority", "III", "2-316", [
    c("exclusions", "Alternative Exclusions Under § 2-316(3)",
      a("asis", "Two familiar expressions excluding implied warranties", "as is or with all faults", "as is and with all faults"),
      a("inspection", "Inspection/refusal affects only defects examination ought to…", "reveal", "have revealed", "disclose"),
      a("practice", "Three practices that may modify implied warranties", "course of dealing course of performance and usage of trade", "COD COP TU")),
    c("priority", "Conflicting Warranties Under § 2-317",
      a("spec", "Prevails over inconsistent sample, model, or general description", "exact or technical specifications", "technical specifications", "exact specifications"),
      a("bulk", "Prevails over inconsistent general description", "sample from an existing bulk", "sample from existing bulk"),
      a("fitness", "Implied warranty not displaced by an inconsistent express warranty", "fitness for a particular purpose", "IWFPP")),
  ], "Finished outline · §§ 2-316–2-317", "Assume no contrary circumstances or overriding consumer law. For warranty priority, first attempt consistent, cumulative construction; then use § 2-317 to determine intent."),
  grid("mmwa-scope", "Magnuson-Moss: Products, Warranties, and Enforcement", "III", "15-2301", [
    c("scope", "Federal Warranty Overlay",
      a("product", "Tangible personal property normally used for…", "personal family or household purposes", "personal family household use"),
      a("consumer", "Consumer includes qualifying transferees during the…", "warranty or service contract period", "duration of the warranty or service contract"),
      a("state", "Source of the underlying implied warranty", "state law", "applicable state law")),
    c("enforcement", "Section 2310",
      a("cure", "Ordinary individual warranty claim: first provide reasonable…", "opportunity to cure", "chance to cure"),
      a("procedure", "Prior resort required if written warranty incorporates a qualifying…", "informal dispute settlement procedure", "FTC compliant dispute procedure"),
      a("fees", "Prevailing consumer may receive reasonable…", "attorney fees and costs", "attorneys fees and costs", "fees and costs")),
  ], "Finished outline · Magnuson-Moss", "Apply §§ 2301 and 2310. The informal procedure must satisfy the FTC requirements and be incorporated as a prerequisite; a fee award remains subject to the court's statutory discretion."),
  grid("mmwa-disclaimers", "Magnuson-Moss: Protecting Implied Warranties", "III", "15-2308", [
    c("triggers", "Supplier Cannot Disclaim Implied Warranties If It…",
      a("written", "Makes this commitment to the consumer", "a written warranty", "written warranty"),
      a("service", "Enters this agreement at sale or within the statutory period", "a service contract", "service contract"),
      a("days", "Post-sale period for the service-contract trigger", "90 days", "ninety days")),
    c("duration", "Permitted Duration Limitation Under § 2308(b)",
      a("reasonable", "Written warranty's duration must be…", "reasonable", "of reasonable duration"),
      a("conscionable", "Limitation itself must be…", "conscionable", "not unconscionable"),
      a("clear", "Required language", "clear and unmistakable", "clear unmistakable language"),
      a("face", "Required display", "prominently on the face of the warranty", "prominent on warranty face")),
  ], "Finished outline · §§ 2304, 2308; Ismael v. Goodman Toyota", "A duration limit is not automatic merely because a limited written warranty has an end date. Full warranties are subject to the stricter § 2304(a)(2) rule."),
  grid("full-warranty", "Federal Minimum Standards for a Full Warranty", "III", "15-2304", [
    c("remedy", "Full Warranty Obligations",
      a("time", "Time allowed to remedy a covered defect", "a reasonable time", "reasonable time"),
      a("cost", "Charge to the consumer for the remedy", "without charge", "free", "no charge"),
      a("duration", "May warrantor limit the duration of an implied warranty?", "no", "no duration limitation"),
      a("damages", "Consequential-damages exclusion must appear…", "conspicuously on the face of the warranty", "conspicuous on the warranty face"),
      a("attempts", "After a reasonable number of failed attempts, consumer may choose…", "refund or replacement", "replacement or refund")),
  ], "Finished outline · §§ 2303–2304", "Recall the full-warranty requirements. These restrictions do not turn the underlying state-law warranty into an unlimited lifetime warranty."),
  grid("limitations", "Sales Claims: Limitations and Accrual", "I and III", "2-725", [
    c("period", "Course's Model UCC Rule",
      a("four", "Default limitations period", "four years", "4 years"),
      a("one", "Shortest period parties may set in original agreement", "one year", "1 year"),
      a("extend", "May parties extend the statutory period by agreement?", "no", "may not extend")),
    c("accrual", "When the Clock Starts",
      a("breach", "General contract claim", "when the breach occurs", "at breach"),
      a("tender", "Ordinary warranty breach", "tender of delivery", "when delivery is tendered"),
      a("future", "Discovery exception requires a warranty explicitly extending to…", "future performance", "future performance of the goods")),
  ], "Finished outline · § 2-725; Gregory Funding v. Saksoft", "Use the model UCC rule assigned in the outline, not a universal state limitations period. The future-performance exception also requires that discovery await that performance."),
];

const privityQuestions = [
  grid("notice", "Notice of Breach After Acceptance", "IV", "2-607", [
    c("requirements", "Preserving a Buyer's Remedy",
      a("recipient", "Give notice to…", "the seller", "seller"),
      a("clock", "Clock starts when buyer discovers or should discover…", "the breach", "breach"),
      a("time", "Notice must follow within…", "a reasonable time", "reasonable time"),
      a("effect", "Failure to notify bars…", "any remedy for the breach", "remedies for breach")),
    c("purpose", "Why Give Notice?",
      a("inspect", "Preserve the seller's chance to examine the problem", "inspection", "inspect the goods", "preserve evidence"),
      a("cure", "Enable correction or mitigation", "opportunity to cure", "cure"),
      a("settle", "Allow negotiated resolution", "settlement", "negotiation"),
      a("repose", "Allow finality after a reasonable interval", "repose", "commercial finality")),
  ], "Finished outline · Notice; Hebron v. American Isuzu", "Applies to buyers after acceptance, including retail buyers. Notice must communicate the claimed breach; timing and any separate notice owed to a remote manufacturer depend on the governing law."),
  grid("vouching-in", "Vouching In a Party Answerable Over", "IV", "2-607", [
    c("procedure", "Section 2-607(5)(a)",
      a("suit", "Trigger: buyer is sued for an obligation for which seller is…", "answerable over", "liable over", "responsible to the buyer"),
      a("writing", "Required form of litigation notice", "written", "written notice", "in writing"),
      a("defend", "Notice must state seller may…", "come in and defend", "defend the suit"),
      a("warning", "Notice must warn of the binding effect of…", "failing to defend", "not defending"),
      a("seasonable", "Notice must be received…", "seasonably", "in a seasonable time"),
      a("bound", "If seller declines, binding findings concern…", "facts common to both litigations", "common factual findings")),
  ], "Finished outline · § 2-607(5)", "A reseller sued on a warranty seeks recourse against its own seller. Vouching in can bind common factual determinations; it does not automatically establish every element of indemnity."),
  grid("privity", "Vertical and Horizontal Privity", "IV", "2-318", [
    c("identify", "Identify the Relationship",
      a("vertical", "Buyer sues upstream manufacturer rather than immediate seller", "vertical privity", "vertical"),
      a("horizontal", "Nonbuyer injured while using buyer's goods", "horizontal privity", "horizontal"),
      a("state", "Remote-manufacturer claims require checking…", "governing state law", "state law", "applicable law")),
    c("boundary", "What Beneficiary Status Does",
      a("who", "§ 2-318 answers this part of the warranty analysis", "who may recover", "who is protected", "beneficiary status"),
      a("breach", "Beneficiary still must establish…", "a breach of warranty causing injury", "breach and causation", "warranty breach and resulting injury")),
  ], "Class 7 · slides 37–39; Finished outline · Crews v. W.A. Brown"),
  grid("privity-alternatives", "Compare the Three Model § 2-318 Alternatives", "IV", "2-318", [
    c("a", "Alternative A",
      a("a-person", "Type of claimant", "natural person", "individual"),
      a("a-relationship", "Required relationship to buyer", "family household member or guest in the home", "family household or houseguest"),
      a("a-harm", "Required kind of injury", "personal injury", "injury to the person")),
    c("b", "Alternative B",
      a("b-person", "Type of reasonably foreseeable claimant", "natural person", "individual"),
      a("b-harm", "Required kind of injury", "personal injury", "injury to the person")),
    c("c", "Alternative C",
      a("c-person", "Type of reasonably foreseeable claimant", "any person", "person including a corporation"),
      a("c-harm", "Injury may include property damage and…", "economic loss", "economic damage"),
      a("c-limit", "Operation cannot be excluded or limited for an individual's…", "personal injury", "injury to the person")),
  ], "Finished outline · § 2-318", "All three require reasonably expected use, consumption, or effect and injury from a warranty breach. States choose or modify alternatives; these are comparisons of the model texts, not three simultaneous rules."),
];

const leaseQuestions = [
  grid("lease-basics", "True Lease, Secured Sale, and Residual Value", "V", "1-203", [
    c("classification", "Substance of the Transaction",
      a("lease", "Transfer of possession and use for a term for consideration", "lease", "true lease"),
      a("residual", "Economic interest retained by a true lessor", "meaningful reversionary interest", "meaningful residual interest", "meaningful residual value"),
      a("article", "Article governing a security interest in a disguised sale", "Article 9", "UCC 9", "9"),
      a("label", "Does calling a transaction a lease determine its legal character?", "no", "substance controls")),
    c("time", "Time of Assessment",
      a("inception", "Assess predictable economic life and value at…", "transaction inception", "when the transaction is entered into", "formation"),
      a("hindsight", "Unexpected later obsolescence alone reclassifies the lease?", "no", "no hindsight")),
  ], "Class 5 · slides 3–8, 22; Class 6 · slides 41–45; Class 7 · slides 13–16", "Compare economic substance, then apply § 1-203. The definition of a lease is in § 2A-103(1)(j)."),
  grid("lease-bright-line", "Lease or Security Interest: Bright-Line Conditions", "V", "1-203", [
    c("gate", "Required Gate Under § 1-203(b)",
      a("obligation", "Lessee's payment obligation for the term is…", "not subject to termination by the lessee", "nonterminable by lessee", "noncancelable by lessee")),
    c("alternatives", "Then Any One of Four Conditions",
      a("life", "Original term compared with remaining economic life", "equal to or greater than remaining economic life", "term consumes remaining economic life"),
      a("bound", "Lessee is bound to renew for remaining life or…", "become the owner", "become owner"),
      a("renew", "Option to renew for remaining life requires no or…", "nominal additional consideration", "nominal consideration"),
      a("buy", "Option to own requires no or…", "nominal additional consideration", "nominal consideration")),
  ], "Class 5 · slides 9–13; Class 6 · slides 17–22", "The nonterminable obligation AND at least one listed condition creates a security interest under the bright-line test. The conditions are alternatives, not cumulative requirements."),
  grid("lease-economics", "Lease Economics After the Bright-Line Test", "V", "1-203", [
    c("economics", "If § 1-203(b) Does Not Resolve Classification",
      a("return", "First course question: reasonable likelihood goods will…", "return to the lessor", "return to lessor"),
      a("value", "Second course question: goods will retain…", "meaningful value", "meaningful residual value"),
      a("nominal", "Compare option price with predictable cost of…", "performing without exercising the option", "not exercising the option")),
    c("nondispositive", "Features That Alone Do Not Create a Security Interest",
      a("net", "Lessee pays taxes, insurance, and maintenance: common label", "net lease", "a net lease"),
      a("payout", "Payments recover substantially the goods' value: common label", "full payout lease", "full payout"),
      a("fmv", "Option at value determined when exercised", "fair market value option", "FMV option")),
  ], "Class 5 · slides 10–13, 22; Class 6 · slides 23–28, 39–47", "Failure of the bright-line test is not an automatic true-lease result. Apply the course's economic-realities inquiry to the facts at inception."),
  grid("lease-application", "Application: Change One Lease Term", "V", "1-203", [
    c("variations", "Assume the Stated Facts Were Predictable at Inception",
      a("base", "Return expected with substantial value; no ownership obligation", "true lease", "lease"),
      a("life", "Nonterminable term uses all remaining economic life", "security interest", "disguised sale", "lease intended as security"),
      a("nominal", "Nonterminable term plus nominal option to own", "security interest", "disguised sale", "lease intended as security"),
      a("expensive", "Only change: lessee pays more than the goods' cash price", "not dispositive", "does not alone create a security interest"),
      a("unexpected", "Only change: unexpected obsolescence two years later", "no reclassification based on hindsight", "no hindsight", "remains a true lease")),
  ], "Class 6 · Problem 2.1; Class 7 · Problem 2.8", "Start with a true lease. Change only the fact stated in each row; assume no other terms alter the result."),
  grid("lease-cases", "Case Applications: Return Rights and the Relevant Goods", "V", "1-203", [
    c("carlson", "Carlson v. Giacchetti",
      a("carlson-result", "Classification despite net/full-payout features", "true lease", "lease"),
      a("carlson-reason", "Key value retained by lessor at term end", "meaningful residual value", "substantial residual value", "reversionary interest")),
    c("purdy", "In re Purdy",
      a("purdy-good", "Relevant asset where replacement cows maintain numbers", "the self-renewing herd", "herd", "renewing herd"),
      a("purdy-result", "Majority's classification", "true lease", "lease")),
    c("bailey", "In re Bailey",
      a("bailey", "Returning equipment while still owing future payments is not a genuine…", "right to terminate", "termination right")),
  ], "Class 5 · slides 23–31; Class 6 · slides 11–13; Carlson and Purdy case PDFs and briefs", "Recall these cases' specific applications. A true lessor's title rights remain subject to applicable transfer rules; do not infer an absolute rule against every third-party buyer."),
  grid("lease-creditors", "Lease Classification and Creditor Consequences", "V", "9-505", [
    c("filing", "Precautionary Filing",
      a("allowed", "May a lessor file a precautionary financing statement?", "yes", "yes without conceding a security interest"),
      a("concession", "Does that filing alone determine that the transaction is secured?", "no", "no classification concession"),
      a("perfection", "If recharacterized, a creditor needs attachment and applicable…", "perfection", "Article 9 perfection")),
    c("rights", "Ownership Versus Collateral",
      a("owner", "Under a true lease, owner of the leased goods", "lessor", "the lessor"),
      a("debtor", "Under a secured sale, buyer owns goods subject to…", "a security interest", "security interest", "a lien"),
      a("limits", "Repossession and bankruptcy recovery remain subject to…", "applicable legal procedures and priorities", "legal procedures and priorities")),
  ], "Class 5 · slides 14–21; Finished outline · Article 9 financing statement", "Classification affects ownership and priority. A financing statement alone does not create an enforceable security interest or authorize immediate repossession in bankruptcy."),
  grid("finance-lease", "Finance Lease: Structure and Qualification", "V", "2A-103", [
    c("roles", "Three-Party Structure",
      a("supplier", "Provides the goods to be leased", "supplier", "the supplier"),
      a("lessor", "Acquires goods or possession/use rights to finance the lease", "lessor", "finance lessor"),
      a("lessee", "Acquires use of the goods under the lease", "lessee", "finance lessee")),
    c("requirements", "Section 2A-103(1)(g)",
      a("selection", "Lessor must not select, manufacture, or…", "supply the goods", "supply"),
      a("acquire", "Lessor's acquisition must be in connection with…", "the lease", "lease transaction"),
      a("disclosure", "Also satisfy at least one statutory…", "disclosure or approval alternative", "disclosure alternative", "approval or disclosure requirement")),
  ], "Finished outline · Finance Lease; Construction Resources v. Element Financial", "First establish a true lease. A lender's involvement or the finance-lease label alone does not establish the statutory classification."),
  grid("finance-disclosure", "Finance Lease: Four Disclosure or Approval Routes", "V", "2A-103", [
    c("routes", "Satisfy One Route in § 2A-103(1)(g)(iii)",
      a("copy", "A · Before signing, lessee receives a copy of the…", "supply contract", "lessor's acquisition contract"),
      a("approve", "B · Effectiveness conditioned on lessee's…", "approval of the supply contract", "approval of acquisition contract"),
      a("statement", "C · Before signing, complete statement of warranties and…", "disclaimers and remedy limitations", "disclaimers limitations and liquidated damages")),
    c("nonconsumer", "D · Nonconsumer Alternative: Written Notice Before Signing",
      a("identity", "Supplier information, unless already selected by lessee", "supplier's identity", "identity of supplier"),
      a("benefit", "Lessee's entitlement to supply-contract…", "promises and warranties", "warranties and promises"),
      a("contact", "Lessee may contact supplier to obtain…", "a complete statement of warranties and limitations", "full warranty and limitation terms")),
  ], "Finished outline · Finance Lease alternatives", "These routes supplement both core finance-lease requirements. Route D is limited to nonconsumer leases; route C also includes third-party warranties and any liquidated-damages terms."),
  grid("finance-promises", "Finance Leases: Warranties and Hell or High Water", "V", "2A-407", [
    c("promise", "Irrevocable and Independent Promises",
      a("scope", "Statutory rule applies to this kind of finance lease", "nonconsumer", "nonconsumer finance lease"),
      a("trigger", "Promises become independent upon lessee's…", "acceptance of the goods", "acceptance"),
      a("pay", "Goods later fail: ordinary payment obligation to finance lessor…", "continues", "must continue paying", "remains enforceable")),
    c("warranties", "Supply Contract · § 2A-209",
      a("beneficiary", "Lessee is a beneficiary of the…", "supply contract", "supplier contract"),
      a("supplier", "Ordinary product-warranty recourse runs against…", "supplier", "the supplier"),
      a("limits", "Passed-through rights remain subject to supply-contract…", "defenses and limitations", "warranty limitations and defenses"),
      a("implied", "Finance lessor automatically gives merchantability/fitness warranties?", "no", "no implied quality warranties")),
  ], "Finished outline · §§ 2A-209, 2A-212–213, 2A-407", "Apply the statutory nonconsumer finance-lease rule. Do not assume every claim against a lessor is waived or that every consumer finance lease has the same statutory payment rule."),
  grid("lease-warranties", "Lease Warranties and Consumer-Lease Boundaries", "V", "2A-214", [
    c("disclaimers", "Ordinary § 2A-214(2) Disclaimer Route",
      a("word", "Merchantability disclaimer must name…", "merchantability", "the word merchantability"),
      a("form", "Merchantability disclaimer must be…", "written and conspicuous", "a conspicuous writing"),
      a("fitness", "Fitness disclaimer must be…", "written and conspicuous", "a conspicuous writing"),
      a("asis", "Article 2A as-is exclusion must also be…", "written and conspicuous", "a conspicuous writing")),
    c("consumer", "Consumer Lease · § 2A-103(1)(e)",
      a("individual", "Lessee must be an…", "individual", "individual person"),
      a("use", "Goods taken primarily for…", "personal family or household purposes", "personal family household use"),
      a("lessor", "Lessor regularly engages in selling or…", "leasing", "leasing goods")),
  ], "Finished outline · §§ 2A-103 and 2A-214", "Assume any monetary limit in the governing state's consumer-lease definition is met. Alternative exclusions and other applicable consumer protections still matter."),
];

const titleQuestions = [
  grid("title-warranty", "Warranty of Title and Infringement", "VI", "2-312", [
    c("title", "Default Title Warranty",
      a("good", "Seller promises title is…", "good", "good title"),
      a("transfer", "Transfer of title must be…", "rightful", "rightful transfer"),
      a("liens", "Goods free from undisclosed security interests, liens, and…", "encumbrances", "other encumbrances"),
      a("seller", "Applies only to merchant sellers?", "no", "all sellers")),
    c("limits", "Disclaimer and Infringement",
      a("specific", "Title disclaimer requires qualifying circumstances or…", "specific language", "specific disclaimer language"),
      a("infringe", "Merchant regularly dealing in such goods warrants against rightful…", "infringement claims", "third party infringement claims")),
  ], "Finished outline · § 2-312", "The lien warranty concerns interests the buyer does not know about at contracting. Infringement protection is subject to agreement and the buyer-supplied-specifications rule."),
  grid("title-transfer", "When Title Passes", "VI", "2-401", [
    c("timing", "Title Is Distinct from Risk of Loss",
      a("identify", "Title cannot pass before goods are…", "identified to the contract", "identified"),
      a("agreement", "First consult the parties' explicit…", "agreement", "agreement on title"),
      a("retained", "Seller's retained title in shipped/delivered goods is limited to…", "a security interest", "security interest")),
    c("default", "Default Physical-Delivery Rules",
      a("shipment", "Shipment contract: title passes at…", "shipment", "time and place of shipment"),
      a("destination", "Destination contract: title passes at…", "tender at destination", "tender of delivery at the destination")),
  ], "Finished outline · § 2-401", "Assume no explicit contrary title agreement and use the default delivery rules. Title alone does not decide risk of loss."),
  grid("voidable-title", "Void and Voidable Title", "VI", "2-403", [
    c("distinctions", "Identify the Transferor's Power",
      a("thief", "Thief takes without any transaction of purchase", "void title", "no title"),
      a("fraud", "Owner delivers in a transaction of purchase induced by fraud", "voidable title", "voidable"),
      a("protected", "Voidable-title holder can give good title to a…", "good faith purchaser for value", "GFPV", "good faith buyer for value")),
    c("examples", "Voidable-Title Examples After Delivery in a Purchase",
      a("check", "Buyer's payment instrument later dishonored", "check", "dishonored check", "bad check"),
      a("identity", "Seller deceived about buyer's…", "identity", "identity of purchaser"),
      a("gift", "Does a mere gift to a good-faith recipient satisfy the value requirement?", "no", "no value given")),
  ], "Finished outline · West v. Roberts", "Voluntary delivery for repair alone is not a transaction of purchase. If entrustment is implicated, analyze its separate requirements."),
  grid("entrustment", "Entrustment and Buyers in Ordinary Course", "VI", "2-403", [
    c("requirements", "Entrustment Under § 2-403(2)",
      a("possession", "Owner entrusts this to the merchant", "possession of the goods", "possession"),
      a("merchant", "Entrustee must be a merchant who…", "deals in goods of that kind", "sells goods of that kind"),
      a("buyer", "Protected transferee", "buyer in ordinary course of business", "BIOCOB", "BOCB"),
      a("rights", "Merchant can transfer all rights of the…", "entruster", "person who entrusted the goods")),
    c("scope", "Meaning and Limits",
      a("retention", "Entrustment includes delivery and acquiescence in…", "retention of possession", "retaining possession"),
      a("knowledge", "Buyer must lack knowledge that the sale violates…", "another person's ownership rights", "third party ownership rights"),
      a("failure", "Failure of entrustment requirements automatically voids all title?", "no", "no apply other title rules")),
  ], "Finished outline · Zaretsky v. William Goldberg Diamond Corp.", "For ordinary-course status also see § 1-201(b)(9): good faith, ordinary-course purchase from a seller of goods of that kind, and the definition's exclusions all matter."),
  grid("title-application", "Application: Stolen, Swindled, or Entrusted?", "VI", "2-403", [
    c("facts", "Choose the Doctrine",
      a("stolen", "Thief steals watch, then sells it to an innocent buyer", "void title", "no title"),
      a("swindled", "Owner delivers watch in a purchase paid by a bad check", "voidable title", "voidable"),
      a("dealer", "Owner leaves watch with watch dealer who sells it in ordinary course", "entrustment", "entrustment rule")),
    c("consequences", "Identify the Missing Requirement",
      a("repair", "Repair-only shop never sells such goods: entrustment fails for lack of…", "dealing in goods of that kind", "merchant dealing in goods of that kind"),
      a("gift", "Swindler gives watch away: protected-purchaser rule lacks…", "value", "purchase for value")),
  ], "Finished outline · § 2-403", "Assume no other title-clearing rule applies. In the dealer variation the buyer satisfies all ordinary-course requirements."),
];

const performanceQuestions = [
  grid("inspection-tender", "Inspection and Perfect Tender", "VII", "2-601", [
    c("tender", "Noninstallment Contract · Subject to Agreement and Cure",
      a("standard", "Goods or tender must conform in…", "every respect", "all respects"),
      a("reject", "Buyer may reject…", "the whole", "all goods", "entire delivery"),
      a("accept", "Buyer may accept…", "the whole", "all goods", "entire delivery"),
      a("units", "Partial acceptance/rejection must respect…", "commercial units", "commercial unit")),
    c("inspection", "Default Inspection Rights · § 2-513",
      a("before", "Inspection generally precedes payment or…", "acceptance", "acceptance of goods"),
      a("reasonable", "Inspection place, time, and manner must be…", "reasonable", "commercially reasonable")),
  ], "Finished outline · §§ 2-513, 2-601", "Assume the contract does not validly alter these defaults. Installment contracts and payment-before-inspection arrangements require separate analysis."),
  grid("rejection", "Effective Rejection and Care of the Goods", "VII", "2-602", [
    c("reject", "Making Rejection Effective",
      a("time", "Reject within this period after delivery or tender", "a reasonable time", "reasonable time"),
      a("notice", "Seasonably notify…", "the seller", "seller"),
      a("ownership", "After rejection, buyer's exercise of ownership is…", "wrongful against the seller", "wrongful")),
    c("custody", "Goods Already in Buyer's Possession",
      a("care", "Hold rejected goods with…", "reasonable care", "reasonable care for the seller"),
      a("period", "Hold long enough to permit seller to…", "remove them", "collect the goods", "take them away"),
      a("merchant", "Merchant buyers may owe additional duties under…", "Section 2-603", "2-603", "UCC 2-603")),
  ]),
  grid("rejected-goods", "Merchant Duties and Unstated Rejection Grounds", "VII", "2-603", [
    c("merchant", "Seller Has No Agent or Business at Place of Rejection",
      a("instructions", "Merchant buyer follows reasonable seller…", "instructions", "disposition instructions"),
      a("perishable", "Without instructions, sell for seller if goods are perishable or…", "threaten to decline in value speedily", "rapidly declining in value"),
      a("effort", "Effort required to make that sale", "reasonable efforts", "reasonable effort")),
    c("grounds", "Failure to Particularize · § 2-605",
      a("cure", "Unstated discoverable defect cannot justify rejection if seller could have…", "cured it if stated seasonably", "cured it with timely notice"),
      a("request", "Between merchants: seller requests a full final statement in…", "writing", "written request")),
  ], "Finished outline · §§ 2-603, 2-605", "Merchant duties apply to goods in the buyer's possession or control. Under § 2-605, waiver of an unstated, reasonably discoverable defect requires one of the specified conditions; it is not automatic for every omitted defect."),
  grid("acceptance", "Acceptance of Goods and Its Effects", "VII", "2-606", [
    c("acts", "Three Routes to Acceptance",
      a("signify", "After reasonable inspection: signify conformity or willingness to…", "take the goods despite nonconformity", "keep nonconforming goods"),
      a("reject", "After reasonable inspection opportunity: fail to make…", "effective rejection", "an effective rejection"),
      a("inconsistent", "Act inconsistent with…", "the seller's ownership", "seller ownership"),
      a("ratification", "If that act is wrongful against seller, acceptance requires seller…", "ratification", "ratifies the act")),
    c("effects", "Sections 2-606(2) and 2-607",
      a("unit", "Accepting part accepts the whole…", "commercial unit", "unit"),
      a("payment", "Buyer must pay at the…", "contract rate", "contract price"),
      a("burden", "Who proves breach for accepted goods?", "buyer", "the buyer"),
      a("remedy", "Acceptance alone eliminates every warranty remedy?", "no", "acceptance does not eliminate warranty remedies")),
  ]),
  grid("cure", "Seller's Two Statutory Opportunities to Cure", "VII", "2-508", [
    c("before", "Time for Performance Has Not Expired",
      a("notify", "Seller must seasonably notify buyer of…", "intent to cure", "intention to cure"),
      a("within", "Make conforming delivery within…", "the contract time", "time for performance")),
    c("after", "Further Reasonable Time Under Subsection (2)",
      a("belief", "Seller had reasonable grounds to believe tender would be…", "acceptable with or without a money allowance", "acceptable with or without allowance"),
      a("notice", "Seller must give seasonable…", "notice", "notice of intent to substitute"),
      a("substitute", "Further reasonable time is for substituting…", "a conforming tender", "conforming goods", "conforming tender")),
    c("scope", "Rejection and Revocation",
      a("rejection", "§ 2-508 expressly addresses which buyer action?", "rejection", "rejecting a tender")),
  ], "Finished outline · § 2-508; cure case discussions", "Do not treat cure after revocation as an automatic § 2-508 entitlement; the outline notes that courts differ on extending cure beyond rejection."),
  grid("revocation", "Revocation of Acceptance", "VII", "2-608", [
    c("grounds", "Threshold and Alternative Grounds",
      a("impair", "Nonconformity must substantially impair value to…", "the buyer", "buyer"),
      a("known", "Known defect: buyer reasonably assumed it would be…", "cured", "seasonably cured"),
      a("failed", "That expected cure did not occur…", "seasonably", "in a seasonable time"),
      a("unknown", "Undiscovered defect: acceptance induced by difficulty of discovery or…", "seller's assurances", "seller assurances")),
    c("procedure", "Time, Condition, and Notice",
      a("time", "Act within a reasonable time of discovery or…", "when buyer should have discovered the ground", "constructive discovery"),
      a("change", "Act before substantial change not caused by…", "the goods' own defects", "own defects", "defects in the goods"),
      a("notice", "Revocation effective only upon notice to…", "the seller", "seller"),
      a("duties", "Revoking buyer has rights and duties of a buyer who…", "rejected the goods", "rejected", "rightfully rejected")),
  ], "Finished outline · § 2-608; North American Lighting", "Revocation is a qualified post-acceptance remedy. A buyer who knowingly accepts a defect ordinarily needs the reasonable-assumption-of-cure route."),
  grid("installments", "Installment Contracts and Substantial Impairment", "VII", "2-612", [
    c("installment", "An Individual Installment",
      a("definition", "Separate deliveries are separately…", "accepted", "accepted by the buyer"),
      a("threshold", "Nonconformity must substantially impair value of…", "that installment", "the installment"),
      a("cure", "Ordinary nonconformity must be one that cannot be…", "cured", "cured seasonably")),
    c("whole", "The Whole Contract",
      a("whole", "Cancellation requires substantial impairment of…", "the whole contract", "value of the whole contract"),
      a("assurance", "Where whole-contract breach is absent, seller's adequate assurance of cure can require…", "acceptance of the installment", "accept installment"),
      a("reinstate", "Accept nonconforming installment without seasonably notifying cancellation: contract…", "is reinstated", "reinstated")),
  ], "Finished outline · § 2-612", "§ 2-612 also permits rejection for a defect in required documents. Keep installment impairment separate from impairment of the whole contract."),
  grid("buyer-remedies", "After Rightful Rejection or Justified Revocation", "VII", "2-711", [
    c("remedies", "Buyer's Available Routes",
      a("cancel", "Buyer may end the contract for breach by…", "cancellation", "canceling", "cancel"),
      a("price", "Buyer may recover price already…", "paid", "paid to the seller"),
      a("cover", "Substitute purchase remedy", "cover", "cover damages"),
      a("nondelivery", "Alternative statutory damages route", "damages for nondelivery", "nondelivery damages")),
    c("security", "Goods in Buyer's Possession or Control",
      a("interest", "Interest securing paid price and qualifying expenses", "security interest", "buyer's security interest"),
      a("expenses", "Qualifying costs: inspection, receipt, transportation, care, and…", "custody", "custody of the goods")),
  ], "Finished outline · § 2-711", "Remedy availability depends on the statutory conditions and the extent of the breach. Rejection or revocation does not categorically bar expectation damages; specific performance or replevin may also be available where their requirements are met."),
];

const riskQuestions = [
  grid("shipment-destination", "Shipment Versus Destination Contracts", "VIII", "2-509", [
    c("shipment", "Shipment Contract",
      a("shipment-fob", "FOB followed by the place of…", "shipment", "shipment origin"),
      a("shipment-risk", "Risk normally passes on due delivery to…", "the carrier", "carrier"),
      a("shipment-contract", "Seller must make a reasonable transportation…", "contract", "shipping contract")),
    c("destination", "Destination Contract",
      a("destination-fob", "FOB followed by the place of…", "destination", "required destination"),
      a("destination-risk", "Risk passes upon due tender at…", "the destination", "required destination"),
      a("receipt", "Is buyer's actual pickup always required at destination?", "no", "no due tender suffices")),
  ], "Finished outline · §§ 2-319, 2-503–504, 2-509", "Assume conforming goods, no contrary risk agreement, and no breach. A carrier contract without a destination-delivery requirement uses the shipment rule."),
  grid("shipping-duties", "Seller's Shipment and Tender Duties", "VIII", "2-504", [
    c("shipment", "Shipment Under § 2-504",
      a("possession", "Put the goods into possession of…", "the carrier", "carrier"),
      a("reasonable", "Make a transportation contract reasonable in light of…", "the nature of the goods and other circumstances", "goods and circumstances"),
      a("documents", "Obtain and promptly deliver or tender necessary…", "documents", "shipping documents"),
      a("notice", "Promptly notify buyer of…", "shipment", "the shipment")),
    c("tender", "Tender Under § 2-503",
      a("available", "Put and hold conforming goods at…", "the buyer's disposition", "buyer disposition"),
      a("notification", "Give notification reasonably necessary to enable buyer to…", "take delivery", "take possession")),
  ], "Finished outline · §§ 2-503–504", "Failure to notify shipment or make a proper transportation contract supports rejection under § 2-504 only if material delay or loss ensues."),
  grid("bailee-risk", "Risk of Loss: Goods Held by a Bailee", "VIII", "2-509", [
    c("routes", "Goods Are to Be Delivered Without Being Moved",
      a("negotiable", "Buyer receives this kind of title document", "negotiable document of title", "negotiable title document"),
      a("acknowledgment", "Bailee acknowledges buyer's right to…", "possession", "possession of goods"),
      a("nonnegotiable", "Nonnegotiable document route also invokes…", "Section 2-503(4)(b)", "2-503(4)(b)", "2-503 4 b")),
    c("qualification", "Nonnegotiable Document or Written Delivery Direction",
      a("present", "Buyer must have reasonable time to present the…", "document or direction", "document", "direction"),
      a("seller", "Risk remains on this party during that reasonable time", "seller", "the seller"),
      a("refusal", "Bailee's refusal to honor the direction defeats…", "the tender", "tender")),
  ], "Finished outline · § 2-509(2)", "Receipt of a nonnegotiable document alone is not the complete risk-transfer rule. Read it with the presentation and bailee-honoring conditions in § 2-503(4)(b)."),
  grid("pickup-risk", "Application: Who Bears the Pickup Loss?", "VIII", "2-509", [
    c("default", "No Carrier or Bailee; No Breach or Contrary Agreement",
      a("merchant", "Merchant seller: transfer event", "buyer's receipt of the goods", "receipt", "physical receipt"),
      a("nonmerchant", "Nonmerchant seller: transfer event", "tender of delivery", "tender")),
    c("apply", "Accidental Fire Before Pickup",
      a("store", "Store has tendered but customer has not received goods: risk bearer", "seller", "store", "merchant seller"),
      a("private", "Private seller has duly tendered: risk bearer", "buyer", "the buyer"),
      a("status", "Whose merchant status controls this distinction?", "seller", "the seller")),
  ], "Finished outline · § 2-509(3)", "Assume the fire is accidental, the goods conform, and all conditions of tender are satisfied. Payment or title alone does not decide the result."),
  grid("breach-risk", "Risk of Loss When a Party Breaches", "VIII", "2-510", [
    c("seller", "Nonconforming Tender Giving a Right to Reject",
      a("seller-risk", "Risk remains on…", "seller", "the seller"),
      a("until", "Until either of these occurs", "cure or acceptance", "acceptance or cure")),
    c("revocation", "Rightful Revocation",
      a("retroactive", "Buyer may treat risk as on seller from…", "the beginning", "the outset"),
      a("buyer-insurance", "Limited to deficiency in whose effective insurance?", "buyer's", "buyer", "buyer's insurance")),
    c("buyer", "Buyer's Breach Before Risk Has Passed",
      a("goods", "Goods must be conforming and…", "identified to the contract", "identified"),
      a("period", "Seller may put risk on buyer for a…", "commercially reasonable time", "commercially reasonable period"),
      a("seller-insurance", "Limited to deficiency in whose effective insurance?", "seller's", "seller", "seller's insurance")),
  ], "Finished outline · § 2-510", "The buyer-breach rule covers repudiation or other breach before ordinary risk transfer. Keep the two different insurance limitations straight."),
];

function flow(id, title, section, rule, prompt, definitions, links, context) {
  const prefix = `sales-${id}`;
  const nodes = definitions.map(([key, x, y, text, clue, kind = "decision", aliases = []]) => ({
    id: `${prefix}-${key}`, x, y, width: 280, height: 100, kind,
    ...(clue === null ? { label: text, quiz: false } : { answer: text, clue, acceptedAnswers: aliases }),
  }));
  const layout = readableFlowchartLayout(nodes);
  return {
    id: prefix, type: "flowchart", avoidNodes: true, title, prompt, ...source(rule),
    courseSources: [`Finished Sales and Leases Outline · ${section}`, context],
    width: 1040, height: layout.height, nodes: layout.nodes,
    arrows: links.map(([from, to, label, rightGutter]) => {
      const fromId = `${prefix}-${from}`;
      const toId = `${prefix}-${to}`;
      const start = layout.nodes.find((node) => node.id === fromId);
      const end = layout.nodes.find((node) => node.id === toId);
      return {
        from: fromId, to: toId, label,
        fromAnchor: rightGutter ? "right" : "bottom",
        toAnchor: rightGutter ? "right" : "top",
        ...(rightGutter ? {
          waypoints: [{ x: rightGutter, y: start.y + start.height / 2 }, { x: rightGutter, y: end.y + end.height / 2 }],
          labelPosition: { x: rightGutter, y: (start.y + start.height + end.y) / 2 },
        } : {}),
      };
    }),
  };
}

formationQuestions.push(flow("forms-path", "Battle of the Forms: Find the Contract", "II", "2-207",
  "Follow an offer and disputed reply. A contract by conduct requires both parties' conduct. Use the Additional Terms drill for subsection (2).",
  [
    ["start", 370, 20, "Does the reply satisfy § 2-207(1)?", null],
    ["valid", 40, 230, "definite and seasonable acceptance", "Required expression", "decision", ["definite and timely acceptance"]],
    ["condition", 700, 230, "expressly conditional on assent to new terms", "Exception to acceptance", "exception", ["expressly conditional acceptance"]],
    ["contract", 40, 450, "contract formed under subsection (1)", "Definite, seasonable, and not expressly conditional", "outcome", ["contract under 2-207(1)"]],
    ["assent", 700, 450, "did the offeror assent to the counteroffer?", "Conditional reply", "decision", ["assent to counteroffer"]],
    ["terms", 40, 670, "analyze additional terms under subsection (2)", "Next step", "rule", ["2-207(2)"]],
    ["agreed", 370, 670, "contract on the assented terms", "Assent given", "outcome", ["contract on agreed terms"]],
    ["conduct", 700, 670, "conduct by both parties recognizes a contract", "No assent: test subsection (3)", "decision", ["both parties perform", "both parties conduct"]],
    ["none", 370, 890, "no contract established on these facts", "No qualifying conduct", "outcome", ["no contract"]],
    ["supplement", 700, 890, "agreed written terms plus UCC supplementary terms", "Contract by conduct", "outcome", ["agreed terms and UCC gap fillers"]],
  ],
  [["start", "valid", "Ordinary reply"], ["start", "condition", "Conditional reply"], ["valid", "contract", "Meets (1)"], ["condition", "assent"], ["contract", "terms"], ["assent", "agreed", "Yes"], ["assent", "conduct", "No"], ["conduct", "none", "No"], ["conduct", "supplement", "Yes"]],
  "Finished outline · § 2-207; Belden v. American Electronic Components"));

leaseQuestions.push(flow("lease-path", "Lease Classification: Bright Line to Economics", "V", "1-203",
  "Start with the lessee's actual payment obligation. Failing the bright-line test does not itself prove a true lease.",
  [
    ["start", 370, 20, "Can the lessee terminate its payment obligation?", null],
    ["conditions", 40, 240, "test the four conditions in Section 1-203(b)", "Nonterminable obligation", "decision", ["four bright line conditions", "1-203(b)"]],
    ["economics", 700, 240, "economic realities test", "No conclusive bright-line result", "decision", ["ERT", "economics of the transaction"]],
    ["security", 40, 480, "security interest", "Any bright-line condition met", "outcome", ["disguised sale"]],
    ["return", 700, 480, "reasonable likelihood of return to lessor", "Economic inquiry: first question", "decision", ["reasonable likelihood goods return", "return to lessor"]],
    ["value", 700, 700, "meaningful residual value", "Economic inquiry: second question", "decision", ["meaningful value", "meaningful reversionary interest"]],
    ["lease", 370, 920, "true lease", "Meaningful return interest retained", "outcome", ["lease"]],
    ["sale", 700, 920, "security interest", "Economics eliminate meaningful reversion", "outcome", ["disguised sale"]],
  ],
  [["start", "conditions", "No"], ["start", "economics", "Yes"], ["conditions", "security", "Any met"], ["conditions", "economics", "None met"], ["economics", "return"], ["return", "value", "Assess both"], ["value", "lease", "Retained"], ["value", "sale", "Eliminated"]],
  "Class 5 · slides 9–13; Class 6 · slides 17–26"));

performanceQuestions.push(flow("rejection-revocation-path", "Choose Rejection or Revocation", "VII", "2-608",
  "Assume a noninstallment sale and no agreement changing the defaults. Inspect, determine acceptance, then apply the appropriate route. See also §§ 2-601–602 and 2-508.",
  [
    ["start", 370, 20, "Has the buyer accepted the goods?", null],
    ["tender", 40, 240, "failure to conform in any respect", "Before acceptance: ordinary tender standard", "decision", ["any nonconformity", "perfect tender"]],
    ["impair", 700, 240, "substantial impairment of value to the buyer", "After acceptance: threshold", "decision", ["substantial impairment to buyer"]],
    ["reject", 40, 460, "timely rejection and seasonable notice", "Rejection procedure", "rule", ["reasonable time and seasonable notice"]],
    ["grounds", 700, 460, "failed expected cure or excusable nondiscovery", "Also need a § 2-608(1) ground", "decision", ["expected cure fails or excusable failure to discover"]],
    ["cure", 40, 680, "consider seller's right to cure", "Before ending the transaction", "exception", ["seller cure", "2-508"]],
    ["revoke", 700, 680, "timely notice before disqualifying change in goods", "If threshold and ground met", "rule", ["reasonable time notice and no disqualifying change"]],
    ["remedies", 370, 920, "buyer's remedies under Section 2-711", "Rightful rejection or justified revocation", "outcome", ["2-711", "buyer remedies"]],
  ],
  [["start", "tender", "No"], ["start", "impair", "Yes"], ["tender", "reject", "Nonconforming"], ["impair", "grounds", "Threshold met"], ["reject", "cure"], ["grounds", "revoke", "Ground met"], ["cure", "remedies", "No effective cure"], ["revoke", "remedies"]],
  "Finished outline · Performance, Tender, Rejection & Revocation"));

riskQuestions.push(flow("risk-path", "Risk of Loss Without Breach: Choose the Route", "VIII", "2-509",
  "First check contrary agreement, sale-on-approval rules, and breach under § 2-510. This chart assumes those do not alter the default and that tender/shipment is proper.",
  [
    ["start", 370, 20, "Which delivery arrangement applies?", null],
    ["carrier", 40, 240, "shipment or destination contract", "Goods shipped by carrier", "decision", ["shipment versus destination"]],
    ["bailee", 370, 240, "Section 2-509(2) and Section 2-503(4)", "Bailee holds goods without movement", "rule", ["2-509(2) and 2-503(4)", "bailee document and acknowledgment rules"]],
    ["other", 700, 240, "is the seller a merchant?", "No carrier or bailee", "decision", ["seller merchant status", "merchant seller"]],
    ["shipment", 40, 510, "due delivery to the carrier", "Shipment contract", "outcome", ["duly delivered to carrier"]],
    ["destination", 370, 510, "due tender at the required destination", "Destination contract", "outcome", ["tender at destination"]],
    ["receipt", 700, 510, "buyer's receipt of the goods", "Merchant seller", "outcome", ["receipt", "physical receipt"]],
    ["tender", 700, 760, "tender of delivery", "Nonmerchant seller", "outcome", ["tender"]],
  ],
  [["start", "carrier", "Carrier"], ["start", "bailee", "Bailee"], ["start", "other", "Neither"], ["carrier", "shipment", "Shipment"], ["carrier", "destination", "Destination"], ["other", "receipt", "Yes"], ["other", "tender", "No", 1010]],
  "Finished outline · Risk of Loss"));

export const salesAndLeasesSubjects = [
  { id: "sales-scope", title: "I. Scope and Applicability", questions: scopeQuestions },
  { id: "sales-formation", title: "II. Contract Formation", questions: formationQuestions },
  { id: "sales-warranties", title: "III. Warranties and Magnuson-Moss", questions: warrantyQuestions },
  { id: "sales-notice-privity", title: "IV. Notice and Privity", questions: privityQuestions },
  { id: "sales-leases", title: "V. Leases and Finance Leases", questions: leaseQuestions },
  { id: "sales-title", title: "VI. Title and Entrustment", questions: titleQuestions },
  { id: "sales-performance", title: "VII. Performance, Rejection, and Revocation", questions: performanceQuestions },
  { id: "sales-risk", title: "VIII. Risk of Loss", questions: riskQuestions },
];
